### ISSUE TITLE
[EPIC] OWF Handover

### ISSUE THREAD

**Issue by alexfigtree** [openwallet-foundation-labs/learner-credential-wallet#568]
https://github.com/openwallet-foundation/project-proposals

Final tasks to complete before handing lcw repo to the OWF GH org:

- [x] proposal template
- [x] #563 
- [x] #562 
- [x] #577 
- [x] #612
- [x] Releases for iOS and iPhone
- [x] credential name issue
- [x] Fork of DCC repo from the OWF (transfer ownership of LCW repo to Tracy)
- [x] Fork back?

**Comment by alexfigtree** [comment]
Dmitri: Hand over LCW to OWF org on GH, then fork that to continue our work

**Comment by alexfigtree** [comment]
Moving #564 and #575 out of this ticket and into backlog, require RN upgrade and are blocked by: #626.

**Comment by alexfigtree** [comment]
Currently waiting for 2 PR approvals on the Open Wallet side.

**Comment by alexfigtree** [comment]
PR's approved by OWF today, still waiting on comments re: code of conduct, change of project name, etc.

**Comment by alexfigtree** [comment]
LCW repo transfer complete - closing!
